### ISSUE TITLE
crash with "meteor clicent"

### ISSUE THREAD

**Issue by Blalala6868** [lovexyn0827/Permanent-Chatlogs#2] opened 2024-01-29 03:25 UTC
Crash Report: https://mclo.gs/5PJRm2U

**Comment by lovexyn0827** [comment] 2024-01-30 14:37
The cause is obvious, but currently i have no idea on how to fix it gracefully ...

**Comment by lovexyn0827** [comment] 2024-01-31 04:31
Fixed in [0.2.2+build20240130](https://modrinth.com/mod/permanent-chatlogs/version/JY3HGjn3)

**Closed by lovexyn0827** 2024-01-31 04:31 UTC
